version: '3.8'

services:
  payment-service:
    container_name: payment-service-ms
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - PORT=4000
        - USE_NON_ROOT_USER=false
    ports:
      - "4001:4000"
    depends_on:
      payment-mysql-ms:
        condition: service_healthy
    env_file:
      - env.development.txt
    networks:
      - payment-network
    volumes:
      - ./backend/src:/app/src
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  payment-mysql-ms:
    container_name: payment-mysql-ms
    image: mysql:8.0
    command: --port=3307
    ports:
      - "3307:3307"
    env_file:
      - env.development.txt
    volumes:
      - payment-mysql-data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - payment-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3307", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  payment-network:
    driver: bridge

volumes:
  payment-mysql-data: 