version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-${STACK_NAME:-prod}
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - codaloo-network
    labels:
      - "com.youmeyou.service=prometheus"
      - "com.youmeyou.environment=${ENVIRONMENT:-production}"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-${STACK_NAME:-prod}
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:-3001}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=metrics.youmeyou.ai
      - GF_SERVER_ROOT_URL=https://metrics.youmeyou.ai
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD}
    networks:
      - codaloo-network
    depends_on:
      - prometheus
    labels:
      - "com.youmeyou.service=grafana"
      - "com.youmeyou.environment=${ENVIRONMENT:-production}"
      - "com.youmeyou.domain=metrics.youmeyou.ai"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-${STACK_NAME:-prod}
    restart: unless-stopped
    ports:
      - "${NODE_EXPORTER_PORT:-9100}:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - codaloo-network
    labels:
      - "com.youmeyou.service=node-exporter"
      - "com.youmeyou.environment=${ENVIRONMENT:-production}"

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  codaloo-network:
    external: true 