version: '3.8'

services:
  # Design Service MongoDB (Internal Only)
  design-mongodb:
    image: mongo:7
    container_name: design-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: design_admin
      MONGO_INITDB_ROOT_PASSWORD: design_mongo_2024!
      MONGO_INITDB_DATABASE: design_service
    volumes:
      - design_mongodb_data:/data/db
      - design_mongodb_config:/data/configdb
      - ./design-mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - youmeyou-data
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Design Service Redis (Internal Only)
  design-redis:
    image: redis:7-alpine
    container_name: design-redis
    restart: unless-stopped
    command: redis-server --requirepass design_redis_2024!
    volumes:
      - design_redis_data:/data
    networks:
      - youmeyou-data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "design_redis_2024!", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Design Service API (Server-level access, Gateway routes publicly)
  design-service:
    image: registry-staging.youmeyou.ai/youmeyou/design-service:latest
    container_name: youmeyou-design-service
    restart: unless-stopped
    environment:
      NODE_ENV: staging
      PORT: 4000
      MONGODB_URI: mongodb://design_admin:design_mongo_2024!@design-mongodb:27017/design_service?authSource=admin
      REDIS_HOST: design-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: design_redis_2024!
      CORS_ORIGIN: "http://localhost:3000,https://staging.youmeyou.ai,https://youmeyou.ai,http://youmeyou-codaloo-web:3000,http://localhost:3002"
      AUTH_SERVICE_URL: http://youmeyou-auth-service:3001
      # AI Configuration
      GEMINI_API_KEY: AIzaSyD4hpoKE-RdZdGYT1lTt_oFEumgvEr4riY  # Primary key for ProjectManager and CasualConversation
      GEMINI_SECONDARY_KEY: AIzaSyBQJ0kQF-ZLc_bTqxjLVqtPVpMBBJvVlvM  # Secondary key for ArchitectureDesigner
      GOOGLE_AI_KEY: AIzaSyD4hpoKE-RdZdGYT1lTt_oFEumgvEr4riY
      A2A_API_KEY: demo-a2a-key
      A2A_PROJECT_ID: codaloo-staging
      # VectorDB Configuration
      CHROMA_URL: http://youmeyou-chromadb:8000
    ports:
      - "4000:4000"  # Server-level access (not public via firewall)
    depends_on:
      - design-mongodb
      - design-redis
    networks:
      - youmeyou-data
      - youmeyou-internal
      - cpu-models-internal
      - vectordb-internal
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  design_mongodb_data:
    driver: local
    name: design_mongodb_data  # Named volume to persist across deployments
  design_mongodb_config:
    driver: local
    name: design_mongodb_config  # Named volume for MongoDB config
  design_redis_data:
    driver: local
    name: design_redis_data  # Named volume for Redis data

networks:
  youmeyou-data:
    external: true
  youmeyou-internal:
    external: true
  cpu-models-internal:
    external: true
    name: cpu-models_cpu-models-internal
  vectordb-internal:
    external: true
    name: vectordb-internal 