version: '3.8'

services:
  # Payment Service MySQL Database (Internal Only)
  payment-mysql:
    image: mysql:8.0
    container_name: youmeyou-payment-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: payment_mysql_root_2024!
      MYSQL_DATABASE: payment_service
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: payment_password_2024!
    volumes:
      - payment_mysql_data:/var/lib/mysql
      - ./payment-mysql-init:/docker-entrypoint-initdb.d
    networks:
      - youmeyou-data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Payment Service Redis (Internal Only)
  payment-redis:
    image: redis:7-alpine
    container_name: youmeyou-payment-redis
    restart: unless-stopped
    command: redis-server --requirepass payment_redis_2024!
    volumes:
      - payment_redis_data:/data
    networks:
      - youmeyou-data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "payment_redis_2024!", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Payment Service API (Server-level access, Gateway routes publicly)
  payment-service:
    image: registry-staging.youmeyou.ai/youmeyou/payment-service:latest
    container_name: youmeyou-payment-service
    restart: unless-stopped
    environment:
      NODE_ENV: staging
      PORT: 6000
      DB_HOST: payment-mysql
      DB_PORT: 3306
      DB_NAME: payment_service
      DB_USER: payment_user
      DB_PASSWORD: payment_password_2024!
      REDIS_HOST: payment-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: payment_redis_2024!
      JWT_SECRET: youmeyou-payment-jwt-secret-staging-2024
      CORS_ORIGIN: "http://localhost:3000,https://staging.youmeyou.ai,https://youmeyou.ai,http://youmeyou-codaloo-web:3000,http://localhost:3002"
      AUTH_SERVICE_URL: http://youmeyou-auth-service:3001
      # Firebase Configuration (Required for payment service)
      FIREBASE_TYPE: service_account
      FIREBASE_PROJECT_ID: sangam-21934
      FIREBASE_PRIVATE_KEY_ID: 4f7eeb6a09bb7b0213f407835d280f64c96a9c4a
      FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDJi6D5/SU8rLXr\nsdayRlonNmiPaNjY+ruW7YkL/WBHvy+ZARleVLBXIgnpQzXImTVEPMz+G8t1/M5U\nqSgHIjio7/+9FDKO4j7pMoikhBbxl2AmFdgmOhFqISQUGdlbe+XrHfVvHTNEgTyg\nBk/UeC1mJZ5OvM2eaCHNOT/F4hjJDAWlYMCRkUPnLfA7JLIdkQkM1DJoDqgGgkut\ngoUuo49mvZ22QVgi2m6wncFhGtTzSKZ8UWNPKL01Ob/pvVyeHJlwhy+vdWkLuFz8\nI6QlltCHCTg5mnXrLUGWQSOsUSdKUKnAwKCD89PXKl2Oiz90dBoyIzhxN0QMPQmk\njtIgO52RAgMBAAECggEACgkI/umUs3mC2JvsrZVeYwCmiPcWtQpNa0c9WuETrJh5\nOj9/wxHccro5j0/PAcOYwpXa1Y90vG88c6K1YR8nF+JU8++cuAvNeupCCE8IOKDp\nvK7ukEvosHjt+I8NvF+ZVyR3iaZrXK6pFVHuVg0vbxw4aBtAJPI/Njfyuo7dEd8p\ndkghAzTU7/mEIopZz6gqUWJ1D+gqTqeGzmKoo1HLptkhg92d5W3wnzP57OTMF6B5\n5carrLEXCcO7eddInAA1N3TGh505o07wR761RJalqCoJe/OdMTBhMA2k9OVcOE2r\nzQTNscAxLsxhlkhwq39seY5FF24XGRmh5SdvLDIOcQKBgQD4RH7xyX2Laf1jKO8d\nzIxtbbl/4Yk/zLyVvBn2SBuy2rNZ6H5CFR5kP92VK2AHpwqF5eW9ngYELfiJU261\nGQJCQhEKIXY6VTdB92OU6CUaFBhu1Z6KBmT8ImFQgJhH0QyZvu3RAAyhBj10Di/E\njuklnVA+//ZNIEq3tAtrg17+ewKBgQDP0prReDn+RzYgzgtwgtH+WQC1+uiFQDfi\nCgVpFsp35DhNdBUqBgchMhGcK0lA7p9JVKprX+0lgWua0VYugteX6fWFK8u/BSkl\nyoZtv+4Np16dHSq2vD3CwFhvHpybH166QOnBohGFHI3877lDe+jY49ABV6Yf154c\nkBJX9LFcYwKBgQDaToDB48d9e+nP9AKvVVp2LvHavVuOul1p3UmHAsk4cI8dFA9R\n1Hgw9ufFb6q1j/D05L8sCXSI4FOXjcHfhOozkRyip+HqUVyRqRPrsGZPlDQX4cfS\n3uSVwTWJMEq3e990oitEiKKSRYZsMr1WPcRNyxLxEuplz2tkNfGEzLQPWQKBgQDJ\ntkaibakMTx4QdSzRRYiA8O4ps6EgRJZ5BPT/bSmTeKXVN4ibQ0KES86f37u4FGPy\njwTiNzc8IgPJPsoBVune/yxY14tomp+3mH0l5RYvlnXU1UxyFP91GbA8GmAyiB4v\ndXXthVqv8mk2SY9uGsSET4nC48nQOj2yx3umd0/2tQKBgD1b60nJqgQJHRPE7t8Y\nSAEmbB/64Jnp/3wAxtX7ZhyNA7Upm7L7Ctr0N9JH/1Y2dSeN/FJQYipVUsnwqtTn\nZyMDdXWTOZYho+Y6ORKyoBdwDNHrHyu9f1p2gGCJJLIB7JKusbB9yLjShKeqRySU\nKu0q3QT89B8xOcon6/k8DSbp\n-----END PRIVATE KEY-----\n"
      FIREBASE_CLIENT_EMAIL: firebase-adminsdk-b8avx@sangam-21934.iam.gserviceaccount.com
      FIREBASE_CLIENT_ID: 117835297085976543210
      FIREBASE_AUTH_URI: https://accounts.google.com/o/oauth2/auth
      FIREBASE_TOKEN_URI: https://oauth2.googleapis.com/token
      FIREBASE_AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
      FIREBASE_CLIENT_X509_CERT_URL: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-b8avx%40sangam-21934.iam.gserviceaccount.com
      FIREBASE_UNIVERSE_DOMAIN: googleapis.com
    ports:
      - "6000:6000"  # Server-level access (not public via firewall)
    depends_on:
      - payment-mysql
      - payment-redis
    networks:
      - youmeyou-data
      - youmeyou-internal
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  payment_mysql_data:
    driver: local
  payment_redis_data:
    driver: local

networks:
  youmeyou-data:
    external: true
  youmeyou-internal:
    external: true 