version: '3.8'

services:
  youmeyou-gateway:
    image: nginx:alpine
    container_name: youmeyou-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/youmeyou/nginx-config/youmeyou-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/youmeyou/ssl-certs:/etc/ssl/certs:ro
      - /opt/youmeyou/nginx-logs:/var/log/nginx
    networks:
      - youmeyou-public
      - youmeyou-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  youmeyou-public:
    external: true
  youmeyou-internal:
    external: true 