# ================================================================================================
# CPU MODELS STACK - OPTIMIZED FOR CLASSIFICATION
# ================================================================================================
# 
# 🚀 RESOURCE OPTIMIZATION:
# - Focused on DistilBERT for classification tasks
# - Lightweight and efficient deployment
# 
# 📊 PERFORMANCE TARGET:
# - DistilBERT: Fast classification (100-300ms)
# - Efficient resource usage on e2-standard-4 VM
#
# 🏗️ SIMPLIFIED ARCHITECTURE:
# - DistilBERT: Task classification and complexity analysis
# - Gateway Service: Request routing and response handling
# ================================================================================================

version: '3.8'

services:
  # CPU Models Gateway - Routes requests to DistilBERT
  cpu-models-gateway-prod:
    image: registry-staging.youmeyou.ai/youmeyou/cpu-models-gateway:latest
    container_name: cpu-models-gateway-prod
    restart: unless-stopped
    ports:
      - "7000:7000"  # Expose gateway port
    environment:
      - NODE_ENV=production
      - PORT=7000
      - DISTILBERT_URL=http://distilbert-service-prod:8002
    networks:
      - youmeyou-internal
      - cpu-models-internal
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # DistilBERT Classification Service
  distilbert-service-prod:
    image: registry-staging.youmeyou.ai/youmeyou/cpu-models-distilbert:latest
    container_name: distilbert-service-prod
    restart: unless-stopped
    environment:
      - MODEL_NAME=distilbert-base-uncased
      - PORT=8002
      - MAX_LENGTH=512
      - PYTHONUNBUFFERED=1
    networks:
      - cpu-models-internal
    volumes:
      - distilbert-models:/app/models
    deploy:
      resources:
        limits:
          cpus: '1.0'  # Increased from 0.3 to 1.0 since we have more resources available
          memory: 2G   # Increased from 1G to 2G for better performance
        reservations:
          cpus: '0.5'  # Increased from 0.2 to 0.5
          memory: 1G   # Increased from 512M to 1G
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8002/health')"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  youmeyou-internal:
    external: true
  cpu-models-internal:
    driver: bridge
    internal: false

volumes:
  distilbert-models:
    driver: local