#!/bin/bash

echo "🔐 Setting up Portainer Registry Authentication"
echo "=============================================="

# Registry configuration (same as used in setup-registry-direct.sh)
REGISTRY_HOST="localhost:5000"
REGISTRY_USER="youmeyou"
REGISTRY_PASS="staging2024!"
PORTAINER_URL="http://34.93.209.77:9000"

echo "📋 Registry Configuration:"
echo "   Registry: ${REGISTRY_HOST}"
echo "   Username: ${REGISTRY_USER}"
echo "   Password: ${REGISTRY_PASS}"
echo ""

echo "🚀 Instructions for Portainer Registry Setup:"
echo ""
echo "1. **Access Portainer UI:**"
echo "   Open: ${PORTAINER_URL}"
echo ""
echo "2. **Add Registry in Portainer:**"
echo "   - Go to 'Registries' in left sidebar"
echo "   - Click '+ Add registry'"
echo "   - Select 'Custom registry'"
echo ""
echo "3. **Registry Configuration:**"
echo "   Name: YouMeYou Registry"
echo "   Registry URL: http://${REGISTRY_HOST}"
echo "   Username: ${REGISTRY_USER}"
echo "   Password: ${REGISTRY_PASS}"
echo ""
echo "4. **Test Registry Connection:**"
echo "   - Click 'Test connection'"
echo "   - Should show 'Success'"
echo "   - Click 'Add registry'"
echo ""
echo "5. **Verify Registry Images:**"
echo "   - Go to 'Images' in Portainer"
echo "   - Should see images from registry:"
echo "     • youmeyou/auth-service:latest"
echo "     • youmeyou/design-service:latest"
echo "     • youmeyou/payment-service:latest"
echo ""

echo "🔍 Alternative: Registry via Docker Login on VM"
echo "If Portainer registry setup doesn't work, SSH to VM and run:"
echo ""
echo "ssh ubuntu@34.93.209.77"
echo "echo '${REGISTRY_PASS}' | docker login ${REGISTRY_HOST} -u ${REGISTRY_USER} --password-stdin"
echo ""

echo "✅ After registry authentication is set up:"
echo "   - Deploy stacks in this order:"
echo "   1. youmeyou-auth (1-auth-microservice.yml)"
echo "   2. youmeyou-design (2-design-microservice.yml)"
echo "   3. youmeyou-payment (3-payment-microservice.yml)"
echo "   4. youmeyou-gateway (4-gateway-service.yml)"
echo ""

echo "🎯 Registry UI: http://34.93.209.77:5001"
echo "   - Check images are available before deploying stacks" 