version: '3.8'

services:
  auth-service:
    image: youmeyou/codaloo-auth:${VERSION:-latest}
    container_name: auth-service-${STACK_NAME:-prod}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=auth-mysql-${STACK_NAME:-prod}
      - DB_PORT=3306
      - DB_NAME=codaloo_auth
      - DB_USER=auth_user
      - DB_PASSWORD=${AUTH_DB_PASSWORD}
      - REDIS_HOST=codaloo-redis-${STACK_NAME:-prod}
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - CORS_ORIGIN=https://youmeyou.ai,https://auth.youmeyou.ai
      - DOMAIN=youmeyou.ai
    ports:
      - "${AUTH_PORT:-3001}:3001"
    networks:
      - codaloo-network
    depends_on:
      - auth-mysql-prod
      - codaloo-redis-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    labels:
      - "com.youmeyou.service=auth-service"
      - "com.youmeyou.environment=${ENVIRONMENT:-production}"
      - "com.youmeyou.domain=auth.youmeyou.ai"

networks:
  codaloo-network:
    external: true 