version: '3.8'

services:
  design-mysql:
    image: mysql:8.0
    container_name: design-mysql-${STACK_NAME:-prod}
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=codaloo_design
      - MYSQL_USER=codaloo_user
      - MYSQL_PASSWORD=${DESIGN_DB_PASSWORD}
    volumes:
      - design_mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "${DESIGN_MYSQL_PORT:-3307}:3306"
    networks:
      - codaloo-network
    command: --default-authentication-plugin=mysql_native_password --max_connections=1000 --innodb_buffer_pool_size=4G
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 6G
        reservations:
          cpus: '1.0'
          memory: 3G
    labels:
      - "com.youmeyou.service=design-database"
      - "com.youmeyou.environment=${ENVIRONMENT:-production}"

volumes:
  design_mysql_data:
    driver: local

networks:
  codaloo-network:
    external: true 